dist: xenial
language: python
python:
  - "3.6"
  
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - python setup.py build

install:
  - pip install -r requirements.txt
  - python setup.py install

before_script:
  - eggpath='/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/SJARACNe-0.2.0-py3.6.egg/SJARACNe/bin'
  - chmod 755 $eggpath/ch_line_ending.py $eggpath/create_consensus_network.py $eggpath/QC_input.py $eggpath/sjaracne.exe

script:
  - python -m pytest -v
  - bats tests
    
#blocklist
branches:
  except:
  - develop
  - SJARACNE-Internal-legacy

#safelist
branches:
  only:
  - master

notifications:
  email: false
