name: netbid2-r44
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - r-base=4.4.3
  - r-biocmanager
  - r-devtools
  - r-remotes
  - r-renv
  - r-matrix
  - r-lme4
  - r-aricode
  - r-igraph
  - r-rcolorbrewer
  - r-plot3d
  - r-plotrix
  - r-umap
  - r-ordinal
  - r-mcmcglmm
  - r-arm
  - r-reshape
  - r-msigdbr
  - r-openxlsx
  - r-rmarkdown
  - r-kableextra
  - r-plotly
  - bioconductor-summarizedexperiment
  - bioconductor-biobase
  - bioconductor-geoquery
  - bioconductor-limma
  - bioconductor-impute
  - bioconductor-tximport
  - bioconductor-deseq2
  - bioconductor-consensusclusterplus
  - bioconductor-complexheatmap
  - bioconductor-biomart
  - bioconductor-gsva
  - bioconductor-rhdf5
  - pandoc
  - compilers
  - make
  - pkg-config
  - git
  - curl
  - libcurl
  - openssl
  - libxml2
  - cairo
  - hdf5
  - zlib
